import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

const glysa = localFont({
  src: '../public/fonts/Glysa.otf',
  variable: "--font-glysa",
})

const LexendDeca = localFont({
  src: '../public/fonts/LexendDeca-VariableFont.ttf',
  variable: "--font-lexend-deca",
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${glysa.variable} ${LexendDeca.variable}`}
      >
        {children}
      </body>
    </html>
  )
}
